//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows;


namespace WpfApp.Net462.I18nRes
{
	public static class ResKeys
	{
		public static readonly ComponentResourceKey test = new ComponentResourceKey(typeof(Resource), nameof(test));
		public static readonly ComponentResourceKey TestString_WithFormat1 = new ComponentResourceKey(typeof(Resource), nameof(TestString_WithFormat1));
		public static readonly ComponentResourceKey TestString_WithFormat3 = new ComponentResourceKey(typeof(Resource), nameof(TestString_WithFormat3));
		public static readonly ComponentResourceKey TestString_WithoutFormat = new ComponentResourceKey(typeof(Resource), nameof(TestString_WithoutFormat));
	}
}