//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Windows;

namespace WpfExtensions.Xaml.Markup
{
    public partial class StylesExtension
    {
		/*
		 * Have to list these constructor overloads here,
		 * because the stupid xaml does not support the "params" keyword.
		 * e.g.: ctor(params Style[] converters) cannot be used.
		 */

		public StylesExtension(Style item0, Style item1)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
		}

		public StylesExtension(Style item0, Style item1, Style item2)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6, Style item7)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
			Styles.Add(item7);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6, Style item7, Style item8)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
			Styles.Add(item7);
			Styles.Add(item8);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6, Style item7, Style item8, Style item9)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
			Styles.Add(item7);
			Styles.Add(item8);
			Styles.Add(item9);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6, Style item7, Style item8, Style item9, Style item10)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
			Styles.Add(item7);
			Styles.Add(item8);
			Styles.Add(item9);
			Styles.Add(item10);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6, Style item7, Style item8, Style item9, Style item10, Style item11)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
			Styles.Add(item7);
			Styles.Add(item8);
			Styles.Add(item9);
			Styles.Add(item10);
			Styles.Add(item11);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6, Style item7, Style item8, Style item9, Style item10, Style item11, Style item12)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
			Styles.Add(item7);
			Styles.Add(item8);
			Styles.Add(item9);
			Styles.Add(item10);
			Styles.Add(item11);
			Styles.Add(item12);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6, Style item7, Style item8, Style item9, Style item10, Style item11, Style item12, Style item13)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
			Styles.Add(item7);
			Styles.Add(item8);
			Styles.Add(item9);
			Styles.Add(item10);
			Styles.Add(item11);
			Styles.Add(item12);
			Styles.Add(item13);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6, Style item7, Style item8, Style item9, Style item10, Style item11, Style item12, Style item13, Style item14)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
			Styles.Add(item7);
			Styles.Add(item8);
			Styles.Add(item9);
			Styles.Add(item10);
			Styles.Add(item11);
			Styles.Add(item12);
			Styles.Add(item13);
			Styles.Add(item14);
		}

		public StylesExtension(Style item0, Style item1, Style item2, Style item3, Style item4, Style item5, Style item6, Style item7, Style item8, Style item9, Style item10, Style item11, Style item12, Style item13, Style item14, Style item15)
		{
			Styles = new StyleCollection();
			Styles.Add(item0);
			Styles.Add(item1);
			Styles.Add(item2);
			Styles.Add(item3);
			Styles.Add(item4);
			Styles.Add(item5);
			Styles.Add(item6);
			Styles.Add(item7);
			Styles.Add(item8);
			Styles.Add(item9);
			Styles.Add(item10);
			Styles.Add(item11);
			Styles.Add(item12);
			Styles.Add(item13);
			Styles.Add(item14);
			Styles.Add(item15);
		}

    }
}
